config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end

  devise_for :users

  authenticated :user do
    root to: "home#dashboard", as: :authenticated_root
  end

  resources :booking_types
  resources :bookings, except: [:index, :new]

  post "payment-intent", to: "bookings#intent"
  get ":booking_link", to: "users#show", as: :user

  scope '/:booking_link', as: :user do
    resources :bookings, only: [:index, :new]
  end

  resources :webhooks, only: :create

  root to: "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # before_action :authenticate_user!, only: :dashboard

  def index
  end

  def dashboard
    @booking_types = current_user.booking_types
    @bookings = Booking.where(booking_type_id: current_user.booking_type_ids)
  end

end

app/views/home/dashboard.html.erb
<div class="container mx-auto px-4 pb-32">
  <div class="flex items-center justify-between pb-6 border-b">
    <h1 class="font-extrabold text-3xl">Dashboard</h1>
    <%= link_to "Create booking type", new_booking_type_path, class: button_class(theme: "primary") %>
  </div>
  <div class="py-10 grid grid-cols-3 gap-6">
    <%= render @booking_types %>
  </div>

  <% if @bookings.pending.any? %>
    <h3 class="font-bold text-2xl mb-6 mt-10 pt-10 border-t border-slate-2">Pending bookings</h3>

    <table class="w-full table-collapse">
      <thead>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Status</th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Name</th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Email</th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Starts</th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Ends</th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Booking Type</th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Premium</th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Paid</th>
      </thead>
      <tbody>
        <%= render @bookings.pending %>
      </tbody>
    </table>
  <% end %>

  <% if @bookings.approved.any? %>
    <h3 class="font-bold text-2xl mb-6 mt-10 pt-10 border-t border-slate-2">Approved bookings</h3>

    <table class="w-full table-collapse">
      <thead>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Status</th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Name</th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Email</th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Starts</th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Ends</th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Booking Type</th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Premium</th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Paid</th>
      </thead>
      <tbody>
        <%= render @bookings.approved %>
      </tbody>
    </table>
  <% end %>

  <% if @bookings.unapproved.any? %>
    <h3 class="font-bold text-2xl mb-6 mt-10 pt-10 border-t border-slate-2">Unapproved bookings</h3>

    <table class="w-full table-collapse">
      <thead>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Status</th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Name</th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Email</th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Starts</th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Ends</th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Booking Type</th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Premium</th>
        <th class="border border-slate-300 p-3 text-left bg-slate-50">Paid</th>
      </thead>
      <tbody>
        <%= render @bookings.unapproved %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="max-w-5xl mx-auto mt-4 lg:p-12 p-4 grid grid-cols-1 lg:grid-cols-12 gap-x-12 gap-y-4 relative z-20">
  <div class="lg:col-span-12 text-center">
    <div class="flex justify-center mb-6">
      <svg fill="none" class="w-16 h-16" height="512" viewBox="0 0 512 512" width="512" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><linearGradient id="a" gradientUnits="userSpaceOnUse" x1="56" x2="463" y1="46" y2="465"><stop offset="0" stop-color="#8038ed"/><stop offset="1" stop-color="#3a0092"/></linearGradient><path d="m0 0h512v512h-512z" fill="#fff"/><rect fill="url(#a)" height="512" rx="110" width="512"/><g stroke="#fff"><circle cx="190" cy="302" r="79.5" stroke-opacity=".9" stroke-width="25"/><circle cx="254" cy="377" r="34" stroke-opacity=".8" stroke-width="10"/><circle cx="282" cy="227" r="106" stroke-width="50"/></g></svg>
    </div>

    <h1 class="mb-4 text-4xl font-semibold text-gray-800 text-center mt-3">Bookme</h1>

    <h2 class="mb-4 text-2xl font-semibold text-gray-800 text-center mt-3">Event Scheduling Application</h2>

<div class="lg:block hidden">
  <svg class="fixed bottom-0 left-0 right-0 z-10" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#5000ca" fill-opacity="1" d="M0,288L60,282.7C120,277,240,267,360,224C480,181,600,107,720,96C840,85,960,139,1080,154.7C1200,171,1320,149,1380,138.7L1440,128L1440,320L1380,320C1320,320,1200,320,1080,320C960,320,840,320,720,320C600,320,480,320,360,320C240,320,120,320,60,320L0,320Z"></path></svg>

  <svg class="fixed bottom-5 left-0 right-0 z-0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#f3f4f5" fill-opacity="1" d="M0,96L48,128C96,160,192,224,288,240C384,256,480,224,576,176C672,128,768,64,864,53.3C960,43,1056,85,1152,90.7C1248,96,1344,64,1392,48L1440,32L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z"></path></svg>
</div>